version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    restart: always

volumes:
  redis-data: