version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME=${APP_NAME:-"FastAPI app"}
      - APP_DESCRIPTION=${APP_DESCRIPTION:-"Your app description"}
      - APP_VERSION=${APP_VERSION:-"1.0.0"}
      - SECRET_KEY=${SECRET_KEY:-"your-secret-key-here"}
      - ALGORITHM=${ALGORITHM:-"HS256"}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS:-7}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY:-"your-clerk-secret-key"}
      - CLERK_SIGNING_SECRET=${CLERK_SIGNING_SECRET:-"your-clerk-signing-secret"}
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - REDIS_CACHE_HOST=redis
      - REDIS_CACHE_PORT=6379
      - REDIS_QUEUE_HOST=redis
      - REDIS_QUEUE_PORT=6379
      - REDIS_RATE_LIMIT_HOST=redis
      - REDIS_RATE_LIMIT_PORT=6379
      - PYTHONPATH=/code/src
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./src/app:/code/app
      - ./src/.env:/code/.env
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    restart: always

volumes:
  redis-data: