"""remove tier field from user

Revision ID: 40be74e6375e
Revises: 8d817d8cad7b
Create Date: 2025-02-25 21:39:21.064218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40be74e6375e'
down_revision: Union[str, None] = '8d817d8cad7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tier_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
