"""Ensure user id is unique

Revision ID: 5c0e43231c13
Revises: c0b46f3a0fc3
Create Date: 2025-02-11 22:14:25.648480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c0e43231c13'
down_revision: Union[str, None] = 'c0b46f3a0fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tokenblacklist_token', table_name='tokenblacklist')
    op.drop_table('tokenblacklist')
    # op.create_foreign_key(None, 'post', 'user', ['created_by_user_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    # op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_table('tokenblacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tokenblacklist_pkey')
    )
    op.create_index('ix_tokenblacklist_token', 'tokenblacklist', ['token'], unique=True)
    # ### end Alembic commands ###
