"""make id user table primary key

Revision ID: d04e0ac2b737
Revises: 4a8e7d2da15d
Create Date: 2025-02-12 13:19:47.678355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04e0ac2b737'
down_revision: Union[str, None] = '4a8e7d2da15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ADD PRIMARY KEY (id);')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" DROP CONSTRAINT user_pkey;')
    # ### end Alembic commands ###
